name: build

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    uses: parcel-bundler/parcel/.github/workflows/native-plugin.yml@core-rs3
    with:
      paths: |
        crates/parcel-plugin-storybook
        crates/parcel-plugin-ts-doc
      publish: true
